masterwork-modifier:
  tips: 0.075
  middle: 0.125
pyrotechnic-modifier:
  blast-strength: 0.2
brewing-items:
  - FERMENTED_SPIDER_EYE
  - RABBIT_FOOT
  - BLAZE_POWDER
  - MAGMA_CREAM
  - GHAST_TEAR
  - NETHER_WART
  - GLOWSTONE_DUST
  - SPIDER_EYE
  - GOLDEN_CARROT
  - GLISTERING_MELON
  - PUFFERFISH
plant-foods:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - COOKIE
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - DRIED_KELP
  - MELON_SLICE
  - CARROT
  - GOLDEN_CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - GLOW_BERRIES
crop-names:
  - WHEAT
  - CARROTS
  - COCOA
  - BEETROOTS
  - POTATOES
  - MELON
  - PUMPKIN
  - NETHER_WART
potions:
  NIGHT_VISION:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  INVISIBILITY:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  JUMP:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  FIRE_RESISTANCE:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  SPEED:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  SLOWNESS:
    default: 90
    extended: 240
    upgraded: 20
    max_amplifier: 3
  WATER_BREATHING:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  POISON:
    default: 45
    extended: 90
    upgraded: 21
    max_amplifier: 1
  REGEN:
    default: 45
    extended: 90
    upgraded: 22
    max_amplifier: 1
  STRENGTH:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  WEAKNESS:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  LUCK:
    default: 300
    extended: 300
    upgraded: 300
    max_amplifier: 0
  SLOW_FALLING:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  CONFUSION:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  SATURATION:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  INSTANT_HEAL:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
  INSTANT_DAMAGE:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
wrangler-mobs:
  - PIG
  - COW
  - CHICKEN
  - HORSE
  - SHEEP
  - AXOLOTL
  - ALLAY
  - BAT
  - BEE
  - CAT
  - DOLPHIN
  - DONKEY
  - FOX
  - GLOW_SQUID
  - GOAT
  - LLAMA
  - MOOSHROOM
  - MULE
  - OCELOT
  - PANDA
  - PARROT
  - POLAR_BEAR
  - RABBIT
  - SQUID
  - STRIDER
  - TRADER_LLAMA
  - TURTLE
  - WOLF
  - FROG
  - CAMEL
  - SNIFFER
trafficker-mobs:
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - SPIDER
  - ENDERMAN
  - ENDERMITE
  - GHAST
  - GUARDIAN
  - HOGLIN
  - HUSK
  - MAGMA_CUBE
  - PHANTOM
  - PIGLIN
  - PIGLIN_BRUTE
  - SILVERFISH
  - SKELETON
  - SLIME
  - SPIDER
  - STRAY
  - VEX
  - WITCH
  - WITHER_SKELETON
  - ZOGLIN
  - ZOMBIE
  - ZOMBIFIED_PIGLIN
excavator-items:
  - DIRT
  - SAND
  - GRAVEL
  - SOUL_SAND
  - SOUL_SOIL
  - ROOTED_DIRT
  - COARSE_DIRT
  - GRASS_BLOCK
  - RED_SAND
  - MYCELIUM
  - PODZOL
archaeologist-loot:
  diamond:
    material: DIAMOND
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  emerald:
    material: EMERALD
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  turtle_egg:
    material: TURTLE_EGG
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SAND
  raw_gold:
    material: RAW_GOLD
    chance: 0.005
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_gold2:
    material: RAW_GOLD
    chance: 0.005
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  gunpowder:
    material: GUNPOWDER
    chance: 0.0025
    min: 2
    max: 6
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.003
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - CLAY
  wither_skull:
    material: WITHER_SKELETON_SKULL
    chance: 0.0001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.005
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SAND
  magma_cream:
    material: MAGMA_CREAM
    chance: 0.005
    min: 1
    max: 3
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  lapis:
    material: LAPIS_LAZULI
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  scute:
    material: SCUTE
    chance: 0.005
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SAND
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.001
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_copper:
    material: RAW_COPPER
    chance: 0.003
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  brick:
    material: BRICK
    chance: 0.003
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - CLAY
  gold_nugget2:
    material: GOLD_NUGGET
    chance: 0.005
    min: 1
    max: 4
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  blaze_rod:
    material: BLAZE_ROD
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  coal:
    material: COAL
    chance: 0.001
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  charcoal:
    material: CHARCOAL
    chance: 0.001
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  gold_nuggets:
    material: GOLD_NUGGET
    chance: 0.003
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_iron:
    material: RAW_IRON
    chance: 0.003
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    blocks:
      - CLAY
  quartz:
    material: QUARTZ
    chance: 0.005
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  glowstone_dust:
    material: GLOWSTONE_DUST
    chance: 0.005
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  red_mushroom:
    material: RED_MUSHROOM
    chance: 0.005
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
  brown_mushroom:
    material: BROWN_MUSHROOM
    chance: 0.005
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
mineral-finder-loot:
  maronine:
    ia: masterwork:maronine_nugget
    min: 1
    max: 1
    chance: 0.005
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  litnium:
    ia: masterwork:litnium_nugget
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  cinnarite:
    ia: masterwork:cinnarite_nugget
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SAND
      - RED_SAND
rare-catch-loot:
  riverfish:
    ia: masterwork:riverfish
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    biomes:
      - RIVER
  shimmerfish:
    ia: masterwork:shimmerfish
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    biomes:
      - WARM_OCEAN
  icefish:
    ia: masterwork:icefish
    chance: 0.005
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    biomes:
      - FROZEN_OCEAN
      - FROZEN_RIVER
      - DEEP_FROZEN_OCEAN
treasure-hunter-loot:
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  quartz:
    material: QUARTZ
    chance: 0.01
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
  diamond:
    material: DIAMOND
    chance: 0.01
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  emerald:
    material: EMERALD
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  ender_pearl:
    material: ENDER_PEARL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  netherite_stuff:
    materials:
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_BOOTS
      - NETHERITE_LEGGINGS
      - NETHERITE_SWORD
      - NETHERITE_AXE
      - NETHERITE_HOE
      - NETHERITE_SHOVEL
      - NETHERITE_PICKAXE
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    random-damage: true
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  heart_of_the_sea:
    material: HEART_OF_THE_SEA
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
  diamond_stuff:
    materials:
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_BOOTS
      - DIAMOND_LEGGINGS
      - DIAMOND_SWORD
      - DIAMOND_AXE
      - DIAMOND_HOE
      - DIAMOND_SHOVEL
      - DIAMOND_PICKAXE
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    random-damage: true
  lapis:
    material: LAPIS_LAZULI
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
  iron_ingot:
    material: IRON_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  copper_ingot:
    material: COPPER_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  coal:
    material: COAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.04
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.01
  disks:
    chance: 0.01
    materials:
      - MUSIC_DISC_13
      - MUSIC_DISC_CAT
      - MUSIC_DISC_BLOCKS
      - MUSIC_DISC_CHIRP
      - MUSIC_DISC_FAR
      - MUSIC_DISC_MALL
      - MUSIC_DISC_MELLOHI
      - MUSIC_DISC_STAL
      - MUSIC_DISC_STRAD
      - MUSIC_DISC_WARD
      - MUSIC_DISC_11
      - MUSIC_DISC_WAIT
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
frenzy-whitelist:
  - DIAMOND_ORE
  - IRON_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - COAL_ORE
  - COPPER_ORE
  - REDSTONE_ORE
  - EMERALD_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_EMERALD_ORE
  - STONE
  - GRANITE
  - ANDESITE
  - DIROITE
  - DEEPSLATE
  - DRIPSTONE_BLOCK
  - CALCITE
  - BASALT
  - BLACKSTONE

messages:
  no-permission: "You do not have permission to execute this command!"
  must-be-hunter: "<red>You must be a hunter to use this mob net!"
  must-be-farmer: "<red>You must be a farmer to use this mob net!"
  must-have-trafficker: "<red>You must have the <yellow>Trafficker Skill<red> to use this item!"
  must-have-wrangler: "<red>You must have the <yellow>Wrangler Skill<red> to use this item!"
  entity-not-in-list-trafficker: "<red>This mob is not on the list of allowed mobs for the <yellow>Trafficker Skill<red>!"
  entity-not-in-list-wrangler: "<red>This mob is not on the list of allowed mobs for the <yellow>Wrangler Skill<red>!"
  no-catch-permission: "<red>You don't have permission to catch mobs in other people's towns without trust!"
